apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: csi.vsphere.vmware.com
    volume.kubernetes.io/provisioner-deletion-secret-name: ""
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
  - kubernetes.io/pv-protection
  name: pvc-1302e074-46fc-4c8d-a019-ecefdaa06518
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-slave-postgres
    namespace: ns-ecs-1-mar-rjs
  csi:
    driver: csi.vsphere.vmware.com
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1709315052678-3114-csi.vsphere.vmware.com
      type: vSphere CNS Block Volume
    volumeHandle: 759f6470-7fe1-4881-9070-7818afe31382
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard-rwo
  volumeMode: Filesystem
